<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\Frontend\AiAssistanceController;
use App\Http\Controllers\Frontend\AiController;
use App\Http\Controllers\Frontend\AiCourseController;
use App\Http\Controllers\Frontend\AiJobsController;
use App\Http\Controllers\Frontend\AiResearchController;
use App\Http\Controllers\Frontend\AndroidController;
use App\Http\Controllers\Frontend\AndroidCourseController;
use App\Http\Controllers\Frontend\AndroidAssistanceController;
use App\Http\Controllers\Frontend\AndroidJobsController;
use App\Http\Controllers\Frontend\AndroidResearchController;
use App\Http\Controllers\Frontend\EighthSemesterAController;
use App\Http\Controllers\Frontend\EighthSemesterBController;
use App\Http\Controllers\Frontend\EighthSemesterCController;
use App\Http\Controllers\Frontend\EighthSemesterController;
use App\Http\Controllers\Frontend\FifthSemesterAController;
use App\Http\Controllers\Frontend\FifthSemesterBController;
use App\Http\Controllers\Frontend\FifthSemesterCController;
use App\Http\Controllers\Frontend\FifthSemesterController;
use App\Http\Controllers\Frontend\FirstSemesterAController;
use App\Http\Controllers\Frontend\FirstSemesterBController;
use App\Http\Controllers\Frontend\FirstSemesterCController;
use App\Http\Controllers\Frontend\FirstSemesterController;
use App\Http\Controllers\Frontend\FourthSemesterAController;
use App\Http\Controllers\Frontend\FourthSemesterBController;
use App\Http\Controllers\Frontend\FourthSemesterCController;
use App\Http\Controllers\Frontend\FourthSemesterController;
use App\Http\Controllers\Frontend\HardwareAssistanceController;
use App\Http\Controllers\Frontend\HardwareController;
use App\Http\Controllers\Frontend\HardwareCourseController;
use App\Http\Controllers\Frontend\HardwareJobsController;
use App\Http\Controllers\Frontend\HardwareResearchController;
use App\Http\Controllers\Frontend\HomeController;
use app\Http\Controllers\Frontend\IotAssistanceController;
use App\Http\Controllers\Frontend\IotController;
use App\Http\Controllers\Frontend\IotCourseController;
use App\Http\Controllers\Frontend\IotJobsController;
use App\Http\Controllers\Frontend\IotResearchController;
use App\Http\Controllers\Frontend\LoginController;
use App\Http\Controllers\Frontend\NetworkingAssistanceController;
use App\Http\Controllers\Frontend\NetworkingController;
use App\Http\Controllers\Frontend\NetworkingCourseController;
use App\Http\Controllers\Frontend\NetworkingResearchController;
use App\Http\Controllers\Frontend\NetwrokingJobsController;
use App\Http\Controllers\Frontend\RegistrationController;
use App\Http\Controllers\Frontend\SecondSemesterAController;
use App\Http\Controllers\Frontend\SecondSemesterBController;
use App\Http\Controllers\Frontend\SecondSemesterCController;
use App\Http\Controllers\Frontend\SecondSemesterController;
use App\Http\Controllers\Frontend\SeventhSemesterAController;
use App\Http\Controllers\Frontend\SeventhSemesterBController;
use App\Http\Controllers\Frontend\SeventhSemesterCController;
use App\Http\Controllers\Frontend\SeventhSemesterController;
use App\Http\Controllers\Frontend\SixthSemesterAController;
use App\Http\Controllers\Frontend\SixthSemesterBController;
use App\Http\Controllers\Frontend\SixthSemesterCController;
use App\Http\Controllers\Frontend\SixthSemesterController;
use App\Http\Controllers\Frontend\ThirdSemesterAController;
use App\Http\Controllers\Frontend\ThirdSemesterBController;
use App\Http\Controllers\Frontend\ThirdSemesterCController;
use App\Http\Controllers\Frontend\ThirdSemesterController;
use App\Http\Controllers\Frontend\WebDevelopingAssistanceController;
use App\Http\Controllers\Frontend\WebDevelopingController;
use App\Http\Controllers\Frontend\WebDevelopingCourseController;
use App\Http\Controllers\Frontend\WebDevelopingJobsController;
use App\Http\Controllers\Frontend\WebDevelopingResearchController;
use App\Http\Controllers\Frontend\NoticeController;
use App\Http\Controllers\Frontend\UserDashboardController;
use App\Http\Controllers\Frontend\TeacherDashboardController;
use App\Http\Controllers\Frontend\AdminDashboardController;
use App\Http\Controllers\Frontend\AdminLoginController;
use App\Http\Controllers\Frontend\TeacherLoginController;
use App\Http\Controllers\Frontend\NewUser;
use App\Http\Controllers\Frontend\AddTeacher;
use App\Http\Controllers\Frontend\AdminCareer;
use App\Http\Controllers\Frontend\AcademicUpdate;
use App\Http\Controllers\Frontend\NewJobOffers;
use App\Http\Controllers\Frontend\NewResearchAssistance;
use App\Http\Controllers\Frontend\NewCourses;
use App\Http\Controllers\Frontend\NewResearchPaper;
use App\Http\Controllers\Frontend\AddNotice;
use App\Http\Controllers\Frontend\NewBooks;
use App\Http\Controllers\Frontend\NewGuideteachers;
use App\Http\Controllers\Frontend\TeacherAddBooks;
use App\Http\Controllers\Frontend\TeacherResearchAssistance;
use App\Http\Controllers\Frontend\TeacherCourses;
use App\Http\Controllers\Frontend\TeacherResearchPapers;
use App\Http\Controllers\Frontend\TeacherNotice;
use App\Http\Controllers\Frontend\UserNotice;
use App\Http\Controllers\Frontend\UserBooks;
use App\Http\Controllers\Frontend\UserAssistance;
use App\Http\Controllers\Frontend\UserCourse;
use App\Http\Controllers\Frontend\UserResearch;
use App\Models\Register;
use App\Models\Admin;
use App\Models\Notice;
use App\Models\Teachers;
use App\Models\Newjob;
use App\Models\Newassistance;
use App\Models\Newcourse;
use App\Models\Newresearchpapers;
use App\Models\Newbook;
use App\Models\Newguide;



/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
Route::get('/',[HomeController::class,'index']);
Route::get('/home',[HomeController::class,'index']);
Route::get('/web-developing',[WebDevelopingController::class,'index'])->middleware('isloggedin');
Route::get('/web-developing-assistance',[WebDevelopingAssistanceController::class,'index'])->middleware('isloggedin');
Route::get('/web-developing-job',[WebDevelopingJobsController::class,'index'])->middleware('isloggedin');
Route::get('/web-developing-course',[WebDevelopingCourseController::class,'index'])->middleware('isloggedin');
Route::get('/web-developing-research',[WebDevelopingResearchController::class,'index'])->middleware('isloggedin');
Route::get('/networking',[NetworkingController::class,'index'])->middleware('isloggedin');
Route::get('/networking-assistance',[NetworkingAssistanceController::class,'index'])->middleware('isloggedin');
Route::get('/networking-job',[NetworkingJobsController::class,'index'])->middleware('isloggedin');
Route::get('/networking-course',[NetworkingCourseController::class,'index'])->middleware('isloggedin');
Route::get('/networking-research',[NetworkingResearchController::class,'index'])->middleware('isloggedin');
Route::get('/iot',[IotController::class,'index'])->middleware('isloggedin');
Route::get('/iot-assistance',[IotAssistanceController::class,'index'])->middleware('isloggedin');
Route::get('/iot-job',[IotJobsController::class,'index'])->middleware('isloggedin');
Route::get('/iot-course',[IotCourseController::class,'index'])->middleware('isloggedin');
Route::get('/iot-research',[IotResearchController::class,'index'])->middleware('isloggedin');
Route::get('/ai',[AiController::class,'index'])->middleware('isloggedin');
Route::get('/ai-assistance',[AiAssistanceController::class,'index'])->middleware('isloggedin');
Route::get('/ai-job',[AiJobsController::class,'index'])->middleware('isloggedin');
Route::get('/ai-course',[AiCourseController::class,'index'])->middleware('isloggedin');
Route::get('/ai-research',[AiResearchController::class,'index'])->middleware('isloggedin');
Route::get('/hardware',[HardwareController::class,'index'])->middleware('isloggedin');
Route::get('/hardware-assistance',[HardwareAssistanceController::class,'index'])->middleware('isloggedin');
Route::get('/hardware-job',[HardwareJobsController::class,'index'])->middleware('isloggedin');
Route::get('/hardware-course',[HardwareCourseController::class,'index'])->middleware('isloggedin');
Route::get('/hardware-research',[HardwareResearchController::class,'index'])->middleware('isloggedin');
Route::get('/android',[AndroidController::class,'index'])->middleware('isloggedin');
Route::get('/android-assistance',[AndroidAssistanceController::class,'index'])->middleware('isloggedin');
Route::get('/android-job',[AndroidJobsController::class,'index'])->middleware('isloggedin');
Route::get('/android-course',[AndroidCourseController::class,'index'])->middleware('isloggedin');
Route::get('/android-research',[AndroidResearchController::class,'index'])->middleware('isloggedin');
Route::get('/1stsemester',[FirstSemesterController::class,'index'])->middleware('isloggedin');
Route::get('/1st_semester-A',[FirstSemesterAController::class,'index'])->middleware('isloggedin');
Route::get('/1st_semester-B',[FirstSemesterBController::class,'index'])->middleware('isloggedin');
Route::get('/1st_semester-C',[FirstSemesterCController::class,'index'])->middleware('isloggedin');
Route::get('/2ndsemester',[SecondSemesterController::class,'index'])->middleware('isloggedin');
Route::get('/2nd_semester-A',[SecondSemesterAController::class,'index'])->middleware('isloggedin');
Route::get('/2nd_semester-B',[SecondSemesterBController::class,'index'])->middleware('isloggedin');
Route::get('/2nd_semester-C',[SecondSemesterCController::class,'index'])->middleware('isloggedin');
Route::get('/3rdsemester',[ThirdSemesterController::class,'index'])->middleware('isloggedin');
Route::get('/3rd_semester-A',[ThirdSemesterAController::class,'index'])->middleware('isloggedin');
Route::get('/3rd_semester-B',[ThirdSemesterBController::class,'index'])->middleware('isloggedin');
Route::get('/3rd_semester-C',[ThirdSemesterCController::class,'index'])->middleware('isloggedin');
Route::get('/4thsemester',[FourthSemesterController::class,'index'])->middleware('isloggedin');
Route::get('/4th_semester-A',[FourthSemesterAController::class,'index'])->middleware('isloggedin');
Route::get('/4th_semester-B',[FourthSemesterBController::class,'index'])->middleware('isloggedin');
Route::get('/4th_semester-C',[FourthSemesterCController::class,'index'])->middleware('isloggedin');
Route::get('/5thsemester',[FifthSemesterController::class,'index'])->middleware('isloggedin');
Route::get('/5th_semester-A',[FifthSemesterAController::class,'index'])->middleware('isloggedin');
Route::get('/5th_semester-B',[FifthSemesterBController::class,'index'])->middleware('isloggedin');
Route::get('/5th_semester-C',[FifthSemesterCController::class,'index'])->middleware('isloggedin');
Route::get('/6thsemester',[SixthSemesterController::class,'index'])->middleware('isloggedin');
Route::get('/6th_semester-A',[SixthSemesterAController::class,'index'])->middleware('isloggedin');
Route::get('/6th_semester-B',[SixthSemesterBController::class,'index'])->middleware('isloggedin');
Route::get('/6th_semester-C',[SixthSemesterCController::class,'index'])->middleware('isloggedin');
Route::get('/7thsemester',[SeventhSemesterController::class,'index'])->middleware('isloggedin');
Route::get('/7th_semester-A',[SeventhSemesterAController::class,'index'])->middleware('isloggedin');
Route::get('/7th_semester-B',[SeventhSemesterBController::class,'index'])->middleware('isloggedin');
Route::get('/7th_semester-C',[SeventhSemesterCController::class,'index'])->middleware('isloggedin');
Route::get('/8thsemester',[EighthSemesterController::class,'index'])->middleware('isloggedin');
Route::get('/8th_semester-A',[EighthSemesterAController::class,'index'])->middleware('isloggedin');
Route::get('/8th_semester-B',[EighthSemesterBController::class,'index'])->middleware('isloggedin');
Route::get('/8th_semester-C',[EighthSemesterCController::class,'index'])->middleware('isloggedin');
Route::get('/notice',[NoticeController::class,'index'])->middleware('isloggedin');
Route::get('/registration',[RegistrationController::class,'index']);
Route::get('/studentupdate',[RegistrationController::class,'index1']);
Route::post('/registration',[RegistrationController::class,'register'])->middleware('isloggedin');
Route::post('/registration',[RegistrationController::class,'store'])->middleware('isloggedin');
Route::post('/registration/view',[RegistrationController::class,'view'])->middleware('isloggedin');
Route::get('/registration-view',[RegistrationController::class,'view'])->middleware('isloggedin');
Route::get('/login',[LoginController::class,'index']);
Route::post('/login',[LoginController::class,'login']);
Route::get('/dashboard',[UserDashboardController::class,'index']);
Route::get('/admin_login',[AdminLoginController::class,'index']);
Route::post('/admin_login',[AdminLoginController::class,'adminlogin']);
Route::get('/admin_dashboard',[AdminDashboardController::class,'index'])->middleware('isloggedin');
Route::get('/teacher_login',[TeacherLoginController::class,'index']);
Route::post('/teacher_login',[TeacherLoginController::class,'teacherlogin']);
Route::get('/add_teacher',[AddTeacher::class,'index'])->middleware('isloggedin');
Route::get('/add_teacher/view',[AddTeacher::class,'view'])->middleware('isloggedin');
Route::get('/add_teacher-view',[AddTeacher::class,'view'])->middleware('isloggedin');
Route::post('/add_teacher',[AddTeacher::class,'store'])->middleware('isloggedin');
Route::get('/add_notice',[AddNotice::class,'index'])->middleware('isloggedin');
Route::get('/add_notice/view',[AddNotice::class,'view'])->middleware('isloggedin');
Route::get('/all_notice_view',[AddNotice::class,'view'])->middleware('isloggedin');
Route::post('/add_notice',[AddNotice::class,'upload'])->middleware('isloggedin');
Route::get('/admin_career',[AdminCareer::class,'index'])->middleware('isloggedin');
Route::get('/academic_update',[AcademicUpdate::class,'index'])->middleware('isloggedin');
Route::get('/new_job_offers',[NewJobOffers::class,'index'])->middleware('isloggedin');
Route::get('/new_job_offers/view',[NewJobOffers::class,'view'])->middleware('isloggedin');
Route::get('/all_job_offers',[NewJobOffers::class,'view'])->middleware('isloggedin');
Route::post('/new_job_offers',[NewJobOffers::class,'store'])->middleware('isloggedin');
Route::get('/new_courses',[NewCourses::class,'index'])->middleware('isloggedin');
Route::get('/new_courses/view',[NewCourses::class,'view'])->middleware('isloggedin');
Route::get('/new_courses-view',[NewCourses::class,'view'])->middleware('isloggedin');
Route::post('/new_courses',[NewCourses::class,'store'])->middleware('isloggedin');
Route::get('/new_research_assistance',[NewResearchAssistance::class,'index'])->middleware('isloggedin');
Route::get('/new_research_assistance/view',[NewResearchAssistance::class,'view'])->middleware('isloggedin');
Route::get('/new_research_assistance-view',[NewResearchAssistance::class,'view'])->middleware('isloggedin');
Route::post('/new_research_assistance',[NewResearchAssistance::class,'store'])->middleware('isloggedin');
Route::get('/new_research_papers',[NewResearchPaper::class,'index'])->middleware('isloggedin');
Route::get('/new_research_papers/view',[NewResearchPaper::class,'view'])->middleware('isloggedin');
Route::get('/all_research_papers',[NewResearchPaper::class,'view'])->middleware('isloggedin');
Route::post('/new_research_papers',[NewResearchPaper::class,'store'])->middleware('isloggedin');
Route::get('/new_books',[NewBooks::class,'index'])->middleware('isloggedin');
Route::get('/new_books/view',[NewBooks::class,'view'])->middleware('isloggedin');
Route::get('/new_books-view',[NewBooks::class,'view'])->middleware('isloggedin');
Route::post('/new_books',[NewBooks::class,'store'])->middleware('isloggedin');
Route::get('/new_guideteacher',[NewGuideteachers::class,'index'])->middleware('isloggedin');
Route::get('/new_guideteacher/view',[NewGuideteachers::class,'view'])->middleware('isloggedin');
Route::get('/new_guideteacher-view',[NewGuideteachers::class,'view'])->middleware('isloggedin');
Route::post('/new_guideteacher',[NewGuideteachers::class,'store'])->middleware('isloggedin');
Route::get('/teacher_dashboard',[TeacherDashboardController::class,'index'])->middleware('isloggedin');
Route::get('/teacher_notice',[TeacherNotice::class,'index'])->middleware('isloggedin');
Route::get('/teacher_addbooks',[TeacherAddBooks::class,'index'])->middleware('isloggedin');
Route::get('/teacher_researchpaper',[TeacherResearchpapers::class,'index'])->middleware('isloggedin');
Route::get('/teacher_researchassistance',[TeacherResearchAssistance::class,'index'])->middleware('isloggedin');
Route::get('/teacher_courses',[TeacherCourses::class,'index'])->middleware('isloggedin');
Route::get('/logout',[AdminLoginController::class,'logout'])->middleware('isloggedin');
Route::get('/approve',[NewResearchPaper::class,'approve'])->middleware('isloggedin');
Route::get('/user_notice',[UserNotice::class,'index'])->middleware('isloggedin');
Route::get('/user_books',[UserBooks::class,'index'])->middleware('isloggedin');
Route::get('/user_assistance',[UserAssistance::class,'index'])->middleware('isloggedin');
Route::get('/user_research',[UserResearch::class,'index'])->middleware('isloggedin');
Route::get('/user_course',[UserCourse::class,'index'])->middleware('isloggedin');
Route::post('/teacher_addbooks',[TeacherAddBooks::class,'store'])->middleware('isloggedin');
Route::post('/teacher_researchpaper',[TeacherResearchPapers::class,'store'])->middleware('isloggedin');
Route::post('/teacher_researchassistance',[TeacherResearchAssistance::class,'store'])->middleware('isloggedin');
Route::post('/teacher_courses',[TeacherCourses::class,'store'])->middleware('isloggedin');
Route::get('/delete_notice/{id}',[AddNotice::class,'delete'])->middleware('isloggedin');
Route::get('/approve_notice/{id}',[Addnotice::class,'approve'])->middleware('isloggedin');
Route::get('/delete_job/{id}',[NewJobOffers::class,'delete'])->middleware('isloggedin');
Route::get('/approve_job/{id}',[NewJobOffers::class,'approve'])->middleware('isloggedin');
Route::get('/delete_user/{id}',[RegistrationController::class,'delete'])->middleware('isloggedin');
Route::get('/approve_user/{id}',[RegistrationController::class,'approve'])->middleware('isloggedin');
Route::get('/delete_assistance/{id}',[NewResearchAssistance::class,'delete'])->middleware('isloggedin');
Route::get('/approve_assistance/{id}',[NewResearchAssistance::class,'approve'])->middleware('isloggedin');
Route::get('/delete_course/{id}',[NewCourse::class,'delete'])->middleware('isloggedin');
Route::get('/approve_course/{id}',[NewCourse::class,'approve'])->middleware('isloggedin');
Route::get('/delete_research/{id}',[NewResearchPaper::class,'delete'])->middleware('isloggedin');
Route::get('/approve_research/{id}',[NewResearchPaper::class,'approve'])->middleware('isloggedin');
Route::get('/approve_book/{id}',[NewBooks::class,'approve'])->middleware('isloggedin');
Route::get('/delete_book/{id}',[NewBooks::class,'delete'])->middleware('isloggedin');
Route::get('/delete_guide/{id}',[NewGuideteachers::class,'delete'])->middleware('isloggedin');
Route::get('/approve_guide/{id}',[NewGuideteachers::class,'approve'])->middleware('isloggedin');